UrentMe/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using UrentMe.Models;
using UrentMe.Util;
namespace UrentMe.Controllers
{
    public class UsuarioController : Controller
    {
        AlquilerCuartosEntities2 bd = new AlquilerCuartosEntities2();
        Utils u = new Utils();

        public ActionResult LoginRegistro()
        {

            //DESTRUYO LAS VARIABLES PARA QUE NO GUARDE LOS DATOS DE SESION LUEGO DE CERRAR SESION
            Session["id_usuario"] = null;
            Session["nom_usuario"] = null;
            Session["tipo_usuario"] = null;
            Session["foto_usuario"] = null;

            return View(new tb_usuario());
        }
        [HttpPost]
        public ActionResult LoginRegistro(tb_usuario usu)
        {

            if (ModelState.IsValid)
            {
                //ESTE OBJETO SERA EN EL FUTURO PARA EL ADMIN
                //var obj1 = "";

                //ESTA LINEA VALIDA SI EL USUARIO DE TIPO ARRENDADOR EXISTE EN LA BD
                var obj2 = bd.tb_usuario.Where(u =>u.email_usuario.Equals(usu.email_usuario) && u.pass_usuario == usu.pass_usuario && u.id_tipo_usuario == 2).FirstOrDefault();
                //ESTA LINEA VALIDA SI EL USUARIO DE TIPO ARRENDATARIO EXISTE EN LA BD
                var obj3 = bd.tb_usuario.Where(u => u.email_usuario.Equals(usu.email_usuario) && u.pass_usuario == usu.pass_usuario && u.id_tipo_usuario == 3).FirstOrDefault();

                if (obj2 != null)
                {
                    //VARIABLES DE SESION PARA EL MENU
                    Session["id_usuario"] = obj2.id_usuario.ToString();
                    Session["nom_usuario"] = obj2.nom_usuario.ToString();
                    Session["tipo_usuario"] = obj2.id_tipo_usuario.ToString();


                    Session["foto_usuario"] = getFoto();
                    

                    return RedirectToAction("../Home/Index");
                }
                else if (obj3 != null)
                {
                    //VARIABLES DE SESION PARA EL MENU
                    Session["id_usuario"] = obj3.id_usuario.ToString();
                    Session["nom_usuario"] = obj3.nom_usuario.ToString();
                    Session["tipo_usuario"] = obj3.id_tipo_usuario.ToString();


                    Session["foto_usuario"] = getFoto();
                    return RedirectToAction("../Home/Index");
                }
                else
                {
                    //SI DEVUELVE NULL, CREA UN NUEVO USUARIO DE TIPO ARRENDADOR
                    usu.id_tipo_usuario = 2;
                    bd.tb_usuario.Add(usu);
                    bd.SaveChanges();


                    var objRep = bd.tb_usuario.Where(u => u.nom_usuario.Equals(usu.nom_usuario) && u.pass_usuario.Equals(usu.pass_usuario) && u.id_tipo_usuario == 2).FirstOrDefault();
                    if (objRep != null)
                    {
                        //VARIABLES DE SESION PARA EL MENU
                        Session["id_usuario"] = objRep.id_usuario.ToString();
                        Session["nom_usuario"] = objRep.nom_usuario.ToString();
                        Session["tipo_usuario"] = objRep.id_tipo_usuario.ToString();
                        Session["foto_usuario"] = objRep.foto_usuario.ToString();
                        return RedirectToAction("../Home/Index");
                    }

                }


            }


            return View();

        }


        public ActionResult Perfil(int id)
        {
            if (Session["id_usuario"] != null)
            {
                tb_usuario u = bd.tb_usuario.Find(id);
                return View(u);
            }
            else
            {
                return RedirectToAction("../Home/Index");
            }
        }
        [HttpPost]
        public ActionResult Perfil(HttpPostedFileBase inputFotoPerfil, [Bind(Include = "nom_usuario,ape_usuario,email_usuario,cel_usuario")] tb_usuario usu)
        {
            if (Session["id_usuario"] != null)
            {
                if(inputFotoPerfil != null)
                {
                    EditFoto(inputFotoPerfil);
                }
                
                tb_usuario uTemporal = bd.tb_usuario.Find(Convert.ToInt32(Session["id_usuario"]));

                uTemporal.nom_usuario = usu.nom_usuario;
                uTemporal.ape_usuario = usu.ape_usuario;
                uTemporal.email_usuario = usu.email_usuario;
                uTemporal.cel_usuario = usu.cel_usuario;



                Session["nom_usuario"] = usu.nom_usuario;
                Session["foto_usuario"] = getFoto();
                
                bd.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            else
            {
                return RedirectToAction("../Home/Index");
            }
        }

        public void EditFoto(HttpPostedFileBase inputFotoPerfil)
        {

            int datos = Int32.Parse(Session["id_usuario"] as String);

            Image i = Image.FromStream(inputFotoPerfil.InputStream, true, true);

            byte[] data = u.imageToByteArray(i);
    
            tb_usuario objUsuario = bd.tb_usuario.First(x => x.id_usuario == datos);
            objUsuario.imagen = data;
            bd.SaveChanges();
        }

        public String getFoto()
        {
            int datos = Int32.Parse(Session["id_usuario"] as String);
            string salida = "";
            tb_usuario u = bd.tb_usuario.First(x => x.id_usuario == datos);
            if (u.imagen != null)
            {
                salida = "data:image/png;base64," +  Convert.ToBase64String(u.imagen);
            }
            else { salida = u.foto_usuario; }

            return salida;

        }







    }
}

UrentMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



    @Scripts.Render("~/bundles/jquery")
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



    @RenderSection("scripts", required: false)
</head>
<body style="padding-top:0px">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    @Html.ActionLink("Inicio", "Index", "Home", new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Acerca de", "About", "Home", new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contacto", "Contact", "Home", new { @class = "nav-link" })
                </li>
            </ul>
            <div class="form-inline my-2 my-lg-0">
                @if (Session["id_usuario"] == null)
                {

                    @Html.ActionLink("Login", "LoginRegistro", "Usuario")

                }
                else
                {

                    @Html.ActionLink(@Session["nom_usuario"].ToString(), "../Usuario/Perfil", new { id = Session["id_usuario"].ToString() }, new { @class = "navbar-brand" })
                    <img class="col-3"  style="border-radius:50%; border: 1px solid white; width:100px;" src="@Session["foto_usuario"].ToString()" alt="" />
                    @Html.ActionLink("Salir", "../Home/Index", new { id = Session["id_usuario"].ToString()}, new { @class = "navbar-brand" })

                }

            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Proyecto Integrador</p>
        </footer>
    </div>

</body>
</html>